language: cpp
addons:
 apt:
   sources:
   - ubuntu-toolchain-r-test
   packages:
   - gcc-4.8
   - g++-4.8
sudo: false
compiler:
  - clang
  - gcc
before_install:
  - git submodule update --init --recursive
script:
  - make cpplint
  - make test
