# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/stanc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/stanc.proto',
  package='stan.proto',
  syntax='proto3',
  serialized_pb=_b('\n\x11proto/stanc.proto\x12\nstan.proto\"U\n\x12StanCompileRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x12\n\nmodel_code\x18\x02 \x01(\t\x12\x17\n\x0fmodel_file_name\x18\x03 \x01(\t\"\xb7\x01\n\x13StanCompileResponse\x12\x34\n\x05state\x18\x02 \x01(\x0e\x32%.stan.proto.StanCompileResponse.State\x12\x10\n\x08\x63pp_code\x18\x03 \x01(\t\x12\x10\n\x08messages\x18\x04 \x01(\t\"F\n\x05State\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0e\n\nINCOMPLETE\x10\x01\x12\x0b\n\x07SUCCESS\x10\x02\x12\x08\n\x04WARN\x10\x03\x12\t\n\x05\x45RROR\x10\x04\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_STANCOMPILERESPONSE_STATE = _descriptor.EnumDescriptor(
  name='State',
  full_name='stan.proto.StanCompileResponse.State',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INCOMPLETE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WARN', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=234,
  serialized_end=304,
)
_sym_db.RegisterEnumDescriptor(_STANCOMPILERESPONSE_STATE)


_STANCOMPILEREQUEST = _descriptor.Descriptor(
  name='StanCompileRequest',
  full_name='stan.proto.StanCompileRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_name', full_name='stan.proto.StanCompileRequest.model_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='model_code', full_name='stan.proto.StanCompileRequest.model_code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='model_file_name', full_name='stan.proto.StanCompileRequest.model_file_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=118,
)


_STANCOMPILERESPONSE = _descriptor.Descriptor(
  name='StanCompileResponse',
  full_name='stan.proto.StanCompileResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='stan.proto.StanCompileResponse.state', index=0,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cpp_code', full_name='stan.proto.StanCompileResponse.cpp_code', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='messages', full_name='stan.proto.StanCompileResponse.messages', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _STANCOMPILERESPONSE_STATE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=304,
)

_STANCOMPILERESPONSE.fields_by_name['state'].enum_type = _STANCOMPILERESPONSE_STATE
_STANCOMPILERESPONSE_STATE.containing_type = _STANCOMPILERESPONSE
DESCRIPTOR.message_types_by_name['StanCompileRequest'] = _STANCOMPILEREQUEST
DESCRIPTOR.message_types_by_name['StanCompileResponse'] = _STANCOMPILERESPONSE

StanCompileRequest = _reflection.GeneratedProtocolMessageType('StanCompileRequest', (_message.Message,), dict(
  DESCRIPTOR = _STANCOMPILEREQUEST,
  __module__ = 'proto.stanc_pb2'
  # @@protoc_insertion_point(class_scope:stan.proto.StanCompileRequest)
  ))
_sym_db.RegisterMessage(StanCompileRequest)

StanCompileResponse = _reflection.GeneratedProtocolMessageType('StanCompileResponse', (_message.Message,), dict(
  DESCRIPTOR = _STANCOMPILERESPONSE,
  __module__ = 'proto.stanc_pb2'
  # @@protoc_insertion_point(class_scope:stan.proto.StanCompileResponse)
  ))
_sym_db.RegisterMessage(StanCompileResponse)


# @@protoc_insertion_point(module_scope)
